CREATE TABLE Kalendarz (ID SERIAL NOT NULL, Pacjent_ID int4 NOT NULL, Nazwa_Kalendarza varchar(255), czy_aktywne bool, PRIMARY KEY (ID));
CREATE TABLE Produkt (ID SERIAL NOT NULL, Kalorycznosc float8, Gramatura float8, Opis varchar(255), czy_pelnowartosciowy bool, Nazwa varchar(255), PRIMARY KEY (ID));
CREATE TABLE Skladnik (Ilosc float8, ProduktID int4 NOT NULL, PosilekID int4 NOT NULL);
CREATE TABLE Jadlospis (ID SERIAL NOT NULL, KalendarzID int4, Data date, Deficyt_Kaloryczny float8, PRIMARY KEY (ID));
CREATE TABLE Dietetyk (ID SERIAL NOT NULL, login varchar(32), password int4, email varchar(64), PRIMARY KEY (ID));
CREATE TABLE Pacjent (ID SERIAL NOT NULL, calendar_id int4, DietetykID int4, poziom_Aktywnosci int4, Waga float8, Wzrost float8, zapotrzebowanie_Kaloryczne float8, uzytkownik_premium bool, Plec int4, data_urodzenia date, login varchar(32), password varchar(255), email varchar(64), PRIMARY KEY (ID));
CREATE TABLE Posilek (ID SERIAL NOT NULL, Nazwa varchar(255), JadlospisID int4 NOT NULL, RodzajPosilku int4 NOT NULL, GodzinaPosilku int4, MinutaPosilku int4, Kalorycznosc float8, PRIMARY KEY (ID));
CREATE TABLE Makroskladnik (ID SERIAL NOT NULL, Nazwa varchar(255), Ilosc float8, ProduktID int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Mikroskladnik (ID SERIAL NOT NULL, Nazwa varchar(255), Ilosc float8, ProduktID int4 NOT NULL, PRIMARY KEY (ID));
ALTER TABLE Posilek ADD CONSTRAINT "sklada sie" FOREIGN KEY (JadlospisID) REFERENCES Jadlospis (ID);
ALTER TABLE Jadlospis ADD CONSTRAINT "jest zlozony z" FOREIGN KEY (KalendarzID) REFERENCES Kalendarz (ID);
ALTER TABLE Kalendarz ADD CONSTRAINT korzysta FOREIGN KEY (Pacjent_ID) REFERENCES Pacjent (ID);
ALTER TABLE Pacjent ADD CONSTRAINT "korzysta z uslug" FOREIGN KEY (DietetykID) REFERENCES Dietetyk (ID);
ALTER TABLE Makroskladnik ADD CONSTRAINT mikroskladnik FOREIGN KEY (ProduktID) REFERENCES Produkt (ID);
ALTER TABLE Mikroskladnik ADD CONSTRAINT makroskladnik FOREIGN KEY (ProduktID) REFERENCES Produkt (ID);
ALTER TABLE Skladnik ADD CONSTRAINT zawiera FOREIGN KEY (ProduktID) REFERENCES Produkt (ID);
ALTER TABLE Skladnik ADD CONSTRAINT "oparty jest o" FOREIGN KEY (PosilekID) REFERENCES Posilek (ID);
alter table pacjent add constraint pacjent_kalendarz__fk foreign key (calendar_id) references kalendarz;
